# Generated by Django 5.1.2 on 2025-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
