# Generated by Django 5.1.2 on 2025-01-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
